name: excellistravel
description: "A Flight Booking App"
publish_to: 'none' 

#production version
# version: 1.0.0+1

#development version
version: 1.0.2+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  
  # Routing
  go_router: ^14.2.7
  
  # HTTP Client
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # Dependency Injection
  get_it: ^8.0.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # UI Components
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  
  # Utils
  equatable: ^2.0.5
  intl: ^0.19.0
  dartz: ^0.10.1
  easy_localization: ^3.0.8
  internet_connection_checker_plus: ^2.7.2

  # Security
  flutter_secure_storage: ^9.2.2

  # Payment Gateway
  razorpay_flutter: ^1.4.0

  # notification
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.4.2

  # Barcode - generator
  barcode: ^2.2.9

  # image picker
  image_picker: ^1.1.2

  #path_provider
  path_provider: ^2.1.4

  # Web view
  webview_flutter: ^4.10.0

  # Network logger
  pretty_dio_logger: ^1.4.0

  #toaster
  fluttertoast: ^8.2.14

  # Image Picker
  dotted_border: ^2.1.0

  #local DB
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #permission handler
  permission_handler: ^11.2.0

  #country code
  country_code_picker: ^3.4.1

  #local  app update
  open_filex: ^4.7.0

  #url_launcher
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter


  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.jpg"
  
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter_18pt-ExtraLight.ttf
          weight: 200
